steps:
  - name: "gcr.io/cloud-builders/go"
    args:
      - "test"
    env:
      - "GOPATH=1.15.6"
  - name: "docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/codeeducation-ci-go:latest"
      - "."

images:
  - "gcr.io/$PROJECT_ID/codeeducation-ci-go:latest"
